const fs = require('fs')

function writeToVariableFile (data) {
  data =
    '/* DO NOT MODIFY. This file is generated by the variableGenerator.js script. */ \n\n\n' +
    data

  return fs.writeFileSync('./src/components/_variables.pcss', data)
}

module.exports = writeToVariableFile
